<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNob7Bwg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNob7Bwg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNob7Bwg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNob7Bwg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNob7Bwg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nob7Bwg',
    'container.build_id' => 'feb29782',
    'container.build_time' => 1771419569,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNob7Bwg');
