<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'customerlist' => [[], ['_controller' => 'App\\Controller\\CustomerController::index'], [], [['text', '/api/customers']], [], [], []],
    'customerorders' => [['customer_id'], ['_controller' => 'App\\Controller\\CustomerController::listOrders'], ['customer_id' => '\\d+'], [['text', '/orders'], ['variable', '/', '\\d+', 'customer_id', true], ['text', '/api/customers']], [], [], []],
    'app_purchase' => [[], ['_controller' => 'App\\Controller\\PurchaseController::index'], [], [['text', '/purchase']], [], [], []],
    'App\Controller\CustomerController::index' => [[], ['_controller' => 'App\\Controller\\CustomerController::index'], [], [['text', '/api/customers']], [], [], []],
    'App\Controller\CustomerController::listOrders' => [['customer_id'], ['_controller' => 'App\\Controller\\CustomerController::listOrders'], ['customer_id' => '\\d+'], [['text', '/orders'], ['variable', '/', '\\d+', 'customer_id', true], ['text', '/api/customers']], [], [], []],
    'App\Controller\PurchaseController::index' => [[], ['_controller' => 'App\\Controller\\PurchaseController::index'], [], [['text', '/purchase']], [], [], []],
];
