<?php

namespace ContainerNob7Bwg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportPurchasesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportPurchasesCommand' shared autowired service.
     *
     * @return \App\Command\ImportPurchasesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportPurchasesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Import/ImportPurchasesService.php';

        $container->privates['App\\Command\\ImportPurchasesCommand'] = $instance = new \App\Command\ImportPurchasesCommand(new \App\Service\Import\ImportPurchasesService(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->privates['App\\Repository\\PurchaseRepository'] ?? $container->load('getPurchaseRepositoryService'))), \dirname(__DIR__, 4));

        $instance->setName('ugo:orders:import');
        $instance->setDescription('Initialize the database from SQL file and import datas using customers/purchases CSV files.');

        return $instance;
    }
}
