<?php

namespace ContainerNob7Bwg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportPurchasesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ImportPurchasesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ImportPurchasesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('ugo:orders:import', [], 'Initialize the database from SQL file and import datas using customers/purchases CSV files.', false, #[\Closure(name: 'App\\Command\\ImportPurchasesCommand')] fn (): \App\Command\ImportPurchasesCommand => ($container->privates['App\\Command\\ImportPurchasesCommand'] ?? $container->load('getImportPurchasesCommandService')));
    }
}
