<?php

namespace ContainerZLtLiPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CustomerController' shared autowired service.
     *
     * @return \App\Controller\CustomerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CustomerController.php';
        include_once \dirname(__DIR__, 4).'/src/Transformer/CustomerToDTOTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Transformer/PurchaseToDTOTransformer.php';

        $container->services['App\\Controller\\CustomerController'] = $instance = new \App\Controller\CustomerController(($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->privates['App\\Repository\\PurchaseRepository'] ?? $container->load('getPurchaseRepositoryService')), new \App\Transformer\CustomerToDTOTransformer(), new \App\Transformer\PurchaseToDTOTransformer());

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\CustomerController', $container));

        return $instance;
    }
}
